#!/bin/bash

source $HOME/development/bash_scripts/shared/indent

DOCKER_USER=$USER
OTHER_ARGUMENTS=()

# Loop through arguments and process them
for arg in "$@"
do
    case $arg in
        -u=*|--docker-user=*)
        DOCKER_USER="${arg#*=}"
        shift
        ;;
        -u|--docker-user)
        DOCKER_USER="$2"
        shift # Remove argument name from processing
        shift # Remove argument value from processing
        ;;
        *)
        OTHER_ARGUMENTS+=("$1")
        shift # Remove generic argument from processing
        ;;
    esac
done

echo  "Instaling Docker with $DOCKER_USER as user"

echo "Downloading Docker intallation script" | indent 
curl -fsSL https://get.docker.com -o get-docker.sh | indent 2

echo "Running Docker intallation script" | indent 
sh get-docker.sh | indent 2

echo "Removing Docker intallation script" | indent 
rm get-docker.sh | indent 2

echo "Adding $DOCKER_USER to docker group" | indent 
sudo usermod -aG docker $DOCKER_USER | indent 2

echo "Docker Installed!"