#!/bin/bash
set -e

failed? () {
    if [$1 -ne 0]; then
        echo "Docker failed to installed! (error: $1)"
        exit $2
    fi
}

echo "Instaling Docker..."

echo "Removing older versions..."
sudo apt-get remove docker \
  docker-engine \
  docker.io \ 
  containerd runc
failed? $? 1

sudo apt-get update
failed? $? 2

echo "Adding Docker’s official GPG key..."
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
failed? $? 3

echo "Adding Docker’s stable repository..."
echo \ 
  "deb [arch=arm64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" \ 
  | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
failed? $? 4

sudo apt-get update
failed? $? 5

echo "Installing packages..."
sudo apt-get install docker-ce docker-ce-cli containerd.io -y
failed? $? 6

echo "Docker Installed!"