#!/bin/bash

mkdir src
mkdir src/assets 
touch src/index.js
touch src/main.css
touch src/index.html

npm init
npm install webpack webpack-cli webpack-dev-server @babel/core babel-loader @babel/preset-env css-loader mini-css-extract-plugin html-loader html-webpack-plugin copy-webpack-plugin --save-dev
npm install phaser

touch webpack.config.js
touch .babelrc
