#!/bin/bash

yarn init
yarn add --dev webpack
yarn add -D babel-loader
yarn add -D @babel/core
yarn add phaser
yarn add -D @babel/preset-env
yarn add -D webpack-dev-server
yarn add -D copy-webpack-plugin
yarn add -D webpack-cli

yarn run webpack
