#!/bin/bash
set -e

DOCKER_USER=$USER
COMPOSE_VERSION=1.29.2
OTHER_ARGUMENTS=( )

failed? () {
    if [$1 -ne 0]; then
        echo "Docker failed to installed! (error: $1)"
        exit $2
    fi
}

# Loop through arguments and process them
for arg in "$@"
do
    case $arg in
        -u=*|--docker-user=*)
        DOCKER_USER="${arg#*=}"
        shift
        ;;
        -u|--docker-user)
        DOCKER_USER="$2"
        shift # Remove argument name from processing
        shift # Remove argument value from processing
        ;;
        -c=*|--compose-version=*)
        COMPOSE_VERSION="${arg#*=}"
        shift
        ;;
        -c|--compose-version)
        COMPOSE_VERSION="$2"
        shift # Remove argument name from processing
        shift # Remove argument value from processing
        ;;
        *)
        OTHER_ARGUMENTS+=("$1")
        shift # Remove generic argument from processing
        ;;
    esac
done

echo  "Instaling Docker for user: $DOCKER_USER"

echo "Removing older versions..."
sudo apt-get remove docker \
  containerd runc
failed? $? 1

sudo apt-get update
failed? $? 2

echo "Adding Docker’s official GPG key..."
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
failed? $? 3

echo "Adding Docker’s stable repository..."
echo \
  "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
  $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
failed? $? 4

sudo apt-get update
failed? $? 5

echo "Installing packages..."
sudo apt-get install docker-ce docker-ce-cli containerd.io -y
failed? $? 6

echo "Adding $DOCKER_USER to docker group..."
sudo usermod -aG docker $DOCKER_USER
failed? $? 7

echo "Docker Installed!"

echo  "Removing old docker-compose versions..."
sudo rm /usr/local/bin/docker-compose
failed? $? 8

echo  "Instaling docker-compose (v$COMPOSE_VERSION) for user: $DOCKER_USER..."
sudo curl -L "https://github.com/docker/compose/releases/download/$COMPOSE_VERSION/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
failed? $? 9

sudo chmod +x /usr/local/bin/docker-compose
failed? $? 10

echo "docker-compose Installed!"
