#!/bin/bash

source $HOME/development/bash_scripts/shared/indent

DOCKER_USER=$USER
OTHER_ARGUMENTS=( )

# Loop through arguments and process them
for arg in "$@"
do
    case $arg in
        -u=*|--docker-user=*)
        DOCKER_USER="${arg#*=}"
        shift
        ;;
        -u|--docker-user)
        DOCKER_USER="$2"
        shift # Remove argument name from processing
        shift # Remove argument value from processing
        ;;
        *)
        OTHER_ARGUMENTS+=("$1")
        shift # Remove generic argument from processing
        ;;
    esac
done

echo  "Instaling Docker for user: $DOCKER_USER"

echo  "Uninstalling old Docker versions"
sudo apt-get remove docker docker-engine docker.io containerd runc

echo  "Updating APT"
sudo apt-get update

echo  "Adding Docker's official GPG Key"
sudo apt-get install \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg \
    lsb-release
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

echo  "Setting up stable repository"
echo \
  "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
  $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

echo "Installing Docker packages"
sudo apt-get update
sudo apt-get install docker-ce docker-ce-cli containerd.io

echo "Adding $DOCKER_USER to docker group"
sudo usermod -aG docker $DOCKER_USER

echo "Docker Installed!"